EMech/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('login.urls')),
    url(r'^mechanics/', include('mechanics.urls')),
    url(r'^services/', include('services.urls')),
    url(r'^garages/', include('garages.urls')),

    url(r'^mechanics-api/', include('mechanics.api.urls'), name="mechanics-api"),
    url(r'^garages-api/', include('garages.api.urls'), name="garages-api"),
]

mechanics/api/urls.py
from django.conf.urls import url
from .views import *
app_name = "mechanics-api"
urlpatterns = [
   # url(r'', MechanicListAPIView.as_view(), name="mechanic-list-api-view"),

    url(r'^all-mechanics/$', MechanicsList.as_view(), name="mechanics-list-create-view"),
    url(r'^all-mechanics/(?P<pk>[0-9]+)/$', MechanicsDetail.as_view(), name="mechanics-list-view"),

]

mechanics/urls.py
from django.conf.urls import url, include

from mechanics.views import all_mechanics, register_mechanic, mechanic_details

app_name = "mechanics"

# url patterns
urlpatterns = [
    url(r'^$', all_mechanics, name="all_mechanics"),
    url(r'^add/$', register_mechanic, name="register_mechanic"),
    url(r'^add/(?P<pk>[0-9]+)/$', mechanic_details, name="mechanic_details"),
]

mechanics/models.py
from django.db import models
from services.models import Services


# Create your models here.
# mechanics table
class Mechanics(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    username = models.CharField(max_length=25)
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=25)

    #service_name = models.ForeignKey(Services,on_delete=models.CASCADE)  # The services model has been imported from the

    # app Services models

    def __str__(self):
        return self.username

mechanics/forms.py
from django import forms
from mechanics.models import Mechanics
from django.contrib.auth.models import User


class RegisterMechanicForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Mechanics
        fields = '__all__'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            match = Mechanics.objects.get(email=email)
        except Mechanics.DoesNotExist:
            return email
        raise forms.ValidationError("The Email is already Registered")

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            match = Mechanics.objects.get(username=username)
        except Mechanics.DoesNotExist:
            return username
        raise forms.ValidationError("Username taken, please try another one")

class UpdateMechanicForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Mechanics
        fields = '__all__'

mechanics/api/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, JsonResponse
from .serializers import MechanicSerializer
from mechanics.models import Mechanics
from rest_framework.generics import ListAPIView, ListCreateAPIView, RetrieveUpdateDestroyAPIView

class MechanicsList(ListCreateAPIView):
    serializer_class = MechanicSerializer
    queryset = Mechanics.objects.all()


class MechanicsDetail(RetrieveUpdateDestroyAPIView):
    serializer_class = MechanicSerializer
    queryset = Mechanics.objects.all()

mechanics/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import RegisterMechanicForm, UpdateMechanicForm
from .models import Mechanics
from django import forms


# Create your views here.

@login_required(login_url='login:login_user')
def all_mechanics(request):
    all_mechanics = Mechanics.objects.all()
    return render(request, 'mechanics/all_mechanics.html', {"all_mechanics": all_mechanics})


def register_mechanic(request):
    if request.method == 'POST':
        form = RegisterMechanicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Mechanic Registered Successfully")
    else:
        form = RegisterMechanicForm()

    return render(request, 'mechanics/register_mechanic.html', {'form': form})


def mechanic_details(request, pk):
    mechanic_instance = get_object_or_404(Mechanics, pk=pk)
    form = UpdateMechanicForm(request.POST or None, instance=mechanic_instance)
    if form.is_valid():
       instance = form.save(commit=False)
       instance.save()
       return redirect("mechanics:register_mechanic")

    context = {
        "form" : form,
        "mechanic_instance" : mechanic_instance,
    }
    return render(request, 'mechanics/register_mechanic.html', context)

mechanics/templates/mechanics/all_mechanics.html
{% extends "services/landing.html" %}

{% block page_title  %} {{ page_name }} {% endblock %}

{% block data_section %}
<div class="row">
    <table class=" w3-table w3-bordered w3-hoverable">
        <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
            <th>Email</th>
        </tr>
        </thead>
        <tbody>
        {% for field in all_mechanics %}
        <tr>
            <td> {{ field.first_name }}</td>
            <td> {{ field.last_name }}</td>
            <td> {{ field.username }}</td>
            <td> {{ field.email }}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
{% endblock data_section %}

mechanics/templates/mechanics/get_mechanic.html
{% extends "services/landing.html" %}

{% block page_title  %} {{ page_name }} {% endblock %}

{% block data_section %}

     <div class="row">
  <form class="col s12" method="post" action="{% url 'mechanics:mechanic_details' mechanic_instance.pk %}">
       {% csrf_token %}
      <label>First Name</label>
      <input type="text" value="{{ mechanic_instance.first_name }}" name="first_name">
      <label>Last Name</label>
      <input type="text" value="{{ mechanic_instance.last_name }}">
      <label>Username</label>
      <input type="text" value="{{ mechanic_instance.username }}">
      <label>Email</label>
      <input type="text" value="{{ mechanic_instance.email }}">
      <input type="submit" name="register_garage" value="Update Mechanic" class="waves-effect waves-light btn">
   </form>

 </div>
{% endblock data_section %}

mechanics/templates/mechanics/register_mechanic.html
{% extends "services/landing.html" %}

{% block page_title  %} {{ page_name }} {% endblock %}

{% block data_section %}
     <div class="row">
   <form class="col s12" method="post" action="">
       {% csrf_token %}
       {{ form }}
       {% if mechanic_instance %}
         <input type="submit" name="register_garage" value="Update Mechanic" class="waves-effect waves-light btn">
       {% else %}
         <input type="submit" name="register_garage" value="Register Mechanic" class="waves-effect waves-light btn">

       {% endif %}
   </form>

 </div>
{% endblock data_section %}