EMech/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('login.urls')),
    url(r'^mechanics/', include('mechanics.urls')),
    url(r'^services/', include('services.urls')),
    url(r'^garages/', include('garages.urls')),

    url(r'^mechanics-api/', include('mechanics.api.urls'), name="mechanics-api"),
    url(r'^garages-api/', include('garages.api.urls'), name="garages-api"),
]

garages/urls.py
from django.conf.urls import url, include

from garages.views import *

app_name = "garages"

# url patterns
urlpatterns = [
    url(r'^$', all_garages, name="all_garages"),
    url(r'^add/$', register_garage, name="register_garage"),
    url(r'^add/(?P<pk>[0-9]+)/$', edit_garage, name="edit_garage"),
]

login/urls.py
from django.conf.urls import url
from .views import *

app_name = "login"

urlpatterns = [
    url(r'^login', login_user, name="login_user"),
    url(r'^logout', logout_user, name="logout_user"),
]

mechanics/urls.py
from django.conf.urls import url, include

from mechanics.views import all_mechanics, register_mechanic, mechanic_details

app_name = "mechanics"

# url patterns
urlpatterns = [
    url(r'^$', all_mechanics, name="all_mechanics"),
    url(r'^add/$', register_mechanic, name="register_mechanic"),
    url(r'^add/(?P<pk>[0-9]+)/$', mechanic_details, name="mechanic_details"),
]

services/urls.py
from django.conf.urls import url
from .views import *

app_name = "services"

urlpatterns = [

    url(r'^$', servicesLanding, name="services-landing"),

    url(r'^car-repair/', carRepair, name="car-repair"),

    url(r'^tow-truck/', towTruck, name="tow-truck"),

    url(r'^medical-help/', medicalHelp, name="medical-help"),
]

services/models.py
from django.db import models


# Create your models here.
# services table

class Services(models.Model):
    service_name = models.CharField(max_length=30)

    def __str__(self):
        return self.service_name

services/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.
@login_required(login_url='login:login_user')
def servicesLanding(request):
    page_name = "Services Dashboard"
    user = User.is_authenticated
    return render(request, 'services/landing.html', {"page_name": page_name, "user": user})


@login_required(login_url='login:login_user')
def carRepair(request):
    page_name = "Car Repair"
    i = 0
    context = {
        "page_name": page_name,
        "i": i
    }

    return render(request, 'services/carRepair.html', {"context": context})


@login_required(login_url='login:login_user')
def towTruck(request):
    name = "Tow truck service coming soon"
    return HttpResponse(name)


@login_required(login_url='login:login_user')
def medicalHelp(request):
    name = "Medical Help service coming soon"
    return HttpResponse(name)

services/templates/services/carRepair.html
{% extends "services/landing.html" %}
{% block page_title  %} {{ page_name }} {% endblock %}

{% block data_section %}
<div class="w3-row-padding">
    <div class="w3-third">
        <h2>Services</h2>
    </div>

    <div class="w3-third" id="search-input">
        <form class="w3-container" action="#" method="get">
            <input class="w3-input w3-border" name="mechsearch" type="text" placeholder="Find a Service">

    </div>
    <div class="w3-third" id="search-btn">
        <button class="w3-btn w3-teal">Search</button>
        </form>
    </div>


    <div class="w3-row">
        <a href="javascript:void(0)" onclick="openTab(event, 'New');">
            <div class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">New</div>
        </a>
        <a href="javascript:void(0)" onclick="openTab(event, 'Complete');">
            <div class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">Complete</div>
        </a>
        <a href="javascript:void(0)" onclick="openTab(event, 'Ongoing');">
            <div class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">Ongoing</div>
        </a>

        <a href="javascript:void(0)" onclick="openTab(event, 'Onhold');">
            <div class="w3-quarter tablink w3-bottombar w3-hover-light-grey w3-padding">Onhold</div>
        </a>
    </div>

    <div id="New" class="w3-container task" style="display:none">
        <table class="w3-table w3-stripped w3-bordered w3-hoverable">
            <tr class="w3-green">
                <th>Customer Name</th>
                <th>Mechanic Name</th>
                <th>Garage Location</th>
                <th>Amount Charged</th>
                <th>Status</th>

            </tr>
            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>
        </table>
    </div>

    <div id="Complete" class="w3-container task" style="display:none">
        <table class="w3-table w3-stripped w3-bordered w3-hoverable">
            <tr class="w3-green">
                <th>Customer Name</th>
                <th>Mechanic Name</th>
                <th>Garage Location</th>
                <th>Amount Charged</th>
                <th>Status</th>

            </tr>
            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>
            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>
        </table>
    </div>

    <div id="Ongoing" class="w3-container task" style="display:none">
        <table class="w3-table w3-stripped w3-bordered w3-hoverable">
            <tr class="w3-green">
                <th>Customer Name</th>
                <th>Mechanic Name</th>
                <th>Garage Location</th>
                <th>Amount Charged</th>
                <th>Status</th>

            </tr>
            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>
        </table>
    </div>
    <div id="Onhold" class="w3-container task" style="display:none">
        <table class="w3-table w3-stripped w3-bordered w3-hoverable">
            <tr class="w3-green">
                <th>Customer Name</th>
                <th>Mechanic Name</th>
                <th>Garage Location</th>
                <th>Amount Charged</th>
                <th>Status</th>

            </tr>
            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>

            <tr>
                <td>John Doe</td>
                <td>Doe John</td>
                <td>Ngara</td>
                <td>15,000</td>
                <td>Complete Icon</td>

            </tr>
        </table>
    </div>
</div>

{% endblock data_section %}

services/templates/services/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block page_title %} {{ page_name }} {% endblock page_title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--import materialize cdn
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
-->

    <!--Import materialize from static -->
    <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/>


    <link rel="stylesheet" href="{% static 'css/w3css.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
{% block body %}
<div class="w3-row">
    <div class="w3-sidebar w3-teal w3-bar-block w3-card">
        <!-- sidebar to the right-->
        <div class="w3-card-4 w3-blue-grey" style="width:100%;">
            <div class="w3-row-padding">
                <div class="w3-col s12">
                    <img src="{% static 'images/img_avatar3.png' %}" class=" w3-left w3-circle w3-margin-right" style="width:60px">
                </div>
                <div class="w3-col s12">
                    <div>
                    <h6>Welcome {{ user.username }} </h6>
                    </div>
                </div>

            </div>
        </div>
        <div class="w3-container" id="sidebar-sub-items">

            <!-- Services accordion-->
            <div class="w3-bar-item " onclick="accFunc2()">
                <div class="w3-row">
                    <div class="w3-col s8">
                      Services
                    </div>
                    <div class="w3-col s4">
                        <i class="fa fa-caret-down"></i>
                    </div>
                </div>

            </div>
            <div id="accSidebar2" class="w3-hide w3-blue-grey">
                <a href="{% url 'services:car-repair' %}" class="w3-bar-item w3-button">Car Repairs</a>
                <a href="{% url 'services:tow-truck' %}" class="w3-bar-item w3-button">Towing</a>
                <a href="{% url 'services:medical-help' %}" class="w3-bar-item w3-button">Medical Services</a>
                <a href="#" class="w3-bar-item w3-button">Reported Accidents</a>
                <a href="#" class="w3-bar-item w3-button">Hire a Driver</a>

            </div>

            <!-- Mechanics accordion-->
            <div class="w3-bar-item" onclick="accFunc()">
                <div class="w3-row">
                    <div class="w3-col s8">
                      Mechanics
                    </div>
                    <div class="w3-col s4">
                        <i class="fa fa-caret-down"></i>
                    </div>
                </div>

            </div>
            <div id="accSidebar" class="w3-hide w3-blue-grey w3-card-4">
                <a href="{% url 'mechanics:all_mechanics' %}" class="w3-bar-item w3-button">All Mechanics</a>
                <a href="{% url 'mechanics:register_mechanic' %}" class="w3-bar-item w3-button">Add New</a>
            </div>

            <!-- Garage accordion-->
            <div class="w3-bar-item" onclick="accFunc1()">
                <div class="w3-row">
                    <div class="w3-col s8">
                      Garage
                    </div>
                    <div class="w3-col s4">
                        <i class="fa fa-caret-down"></i>
                    </div>
                </div>
            </div>
            <div id="accSidebar1" class="w3-hide w3-blue-grey w3-card-4">
                <a href=" {% url 'garages:all_garages' %}" class="w3-bar-item w3-button">All Garages</a>
                <a href="{% url 'garages:register_garage' %}" class="w3-bar-item w3-button">Add New </a>
                <a href="#" class="w3-bar-item w3-button">Edit</a>
            </div>

        </div>

    </div>
    <!-- -->
    <div class="w3-container" id="maincontent">
        <!-- body with content from selected menu item-->
        <div class="w3-bar w3-indigo w3-large" id="topbar">
            <a href="#" class="w3-bar-item">Home</a>
            <a href="#" class="w3-bar-item w3-display-topmiddle">Top Navigation</a>
            <a href="{% url 'login:logout_user' %}" class="w3-bar-item w3-display-topright">Logout</a>
        </div>
        {% block data_section %}

        {% endblock data_section %}
    </div>
    <!-- -->

</div>


<script src=" {% static 'js/script.js' %}"></script>
<script src=" {% static 'js/script.js' %}"></script>
  <!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src=" {% static 'materialize/js/materialize.min.js'%}"></script>
{% endblock body%}
</body>
</html>